from __future__ import annotations

from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from sose.core.events import Command, DomainEvent
from sose.core.runtime import ScheduledWork, SimulationPosition
from sose.domain.entity import Entity
from sose.scenarios.model import ScenarioRuntimeState


class UnitOfWork(Protocol):
    def get_entity(self, entity_type: str, entity_id: str) -> Entity | None: ...
    def save_entity(self, entity: Entity) -> None: ...
    def append_event(self, event: DomainEvent) -> None: ...
    def get_command(self, command_id: str) -> Command | None: ...
    def save_command(self, command: Command) -> None: ...
    def delete_command(self, command_id: str) -> None: ...
    def get_scheduled_work(self, work_id: str) -> ScheduledWork | None: ...
    def save_scheduled_work(self, work: ScheduledWork) -> None: ...
    def delete_scheduled_work(self, work_id: str) -> None: ...
    def set_simulation_position(self, position: SimulationPosition) -> None: ...
    def set_scenario_state(self, state: ScenarioRuntimeState) -> None: ...
    def set_committed_tick(self, tick: int) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class Persistence(Protocol):
    def transaction(self) -> AbstractContextManager[UnitOfWork]: ...
    def committed_tick(self) -> int: ...
    def events(self) -> tuple[DomainEvent, ...]: ...
    def command(self, command_id: str) -> Command | None: ...
    def scheduled_work(self) -> tuple[ScheduledWork, ...]: ...
    def due_scheduled_work(self, at: datetime) -> tuple[ScheduledWork, ...]: ...
    def simulation_position(self) -> SimulationPosition | None: ...
    def scenario_state(self) -> ScenarioRuntimeState | None: ...
