from __future__ import annotations

from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from sose.core.events import Command, DomainEvent
from sose.core.runtime import (
    ResourceDefinition,
    ResourceDemand,
    ResourceReleaseIntent,
    ResourceReservation,
    StoreDefinition,
    DurableStoreItem,
    StorePutIntent,
    StoreGetRequest,
    StoreGetResult,
    ContainerDefinition,
    ContainerState,
    ContainerOperationIntent,
    ContainerOperationResult,
    PreemptiveResourceDefinition,
    PreemptiveResourceDemand,
    PreemptiveResourceReservation,
    PreemptiveResourceReleaseIntent,
    ResourcePreemptionResult,
    ScheduledWork,
    SimulationPosition,
)
from sose.domain.entity import Entity
from sose.scenarios.model import ScenarioRuntimeState


class UnitOfWork(Protocol):
    def get_entity(self, entity_type: str, entity_id: str) -> Entity | None: ...
    def save_entity(self, entity: Entity) -> None: ...
    def append_event(self, event: DomainEvent) -> None: ...
    def get_command(self, command_id: str) -> Command | None: ...
    def save_command(self, command: Command) -> None: ...
    def delete_command(self, command_id: str) -> None: ...
    def get_scheduled_work(self, work_id: str) -> ScheduledWork | None: ...
    def save_scheduled_work(self, work: ScheduledWork) -> None: ...
    def delete_scheduled_work(self, work_id: str) -> None: ...
    def set_simulation_position(self, position: SimulationPosition) -> None: ...
    def set_scenario_state(self, state: ScenarioRuntimeState) -> None: ...
    def get_resource_demand(self, request_id: str) -> ResourceDemand | None: ...
    def save_resource_definition(self, definition: ResourceDefinition) -> None: ...
    def save_resource_demand(self, demand: ResourceDemand) -> None: ...
    def delete_resource_demand(self, request_id: str) -> None: ...
    def get_resource_reservation(self, reservation_id: str) -> ResourceReservation | None: ...
    def save_resource_reservation(self, reservation: ResourceReservation) -> None: ...
    def delete_resource_reservation(self, reservation_id: str) -> None: ...
    def get_resource_release_intent(self, intent_id: str) -> ResourceReleaseIntent | None: ...
    def save_resource_release_intent(self, intent: ResourceReleaseIntent) -> None: ...
    def delete_resource_release_intent(self, intent_id: str) -> None: ...
    def get_store_item(self, item_id: str) -> DurableStoreItem | None: ...
    def get_store_put_intent(self, item_id: str) -> StorePutIntent | None: ...
    def get_store_get_request(self, request_id: str) -> StoreGetRequest | None: ...
    def get_store_get_result(self, request_id: str) -> StoreGetResult | None: ...
    def save_store_definition(self, definition: StoreDefinition) -> None: ...
    def save_store_item(self, item: DurableStoreItem) -> None: ...
    def delete_store_item(self, item_id: str) -> None: ...
    def save_store_put_intent(self, intent: StorePutIntent) -> None: ...
    def delete_store_put_intent(self, item_id: str) -> None: ...
    def save_store_get_request(self, request: StoreGetRequest) -> None: ...
    def delete_store_get_request(self, request_id: str) -> None: ...
    def save_store_get_result(self, result: StoreGetResult) -> None: ...
    def get_container_state(self, name: str) -> ContainerState | None: ...
    def get_container_operation_intent(self, request_id: str) -> ContainerOperationIntent | None: ...
    def get_container_operation_result(self, request_id: str) -> ContainerOperationResult | None: ...
    def save_container_definition(self, definition: ContainerDefinition) -> None: ...
    def save_container_state(self, state: ContainerState) -> None: ...
    def save_container_operation_intent(self, intent: ContainerOperationIntent) -> None: ...
    def delete_container_operation_intent(self, request_id: str) -> None: ...
    def save_container_operation_result(self, result: ContainerOperationResult) -> None: ...
    def get_preemptive_resource_demand(self, request_id: str) -> PreemptiveResourceDemand | None: ...
    def get_preemptive_resource_reservation(self, reservation_id: str) -> PreemptiveResourceReservation | None: ...
    def get_preemptive_resource_release_intent(self, intent_id: str) -> PreemptiveResourceReleaseIntent | None: ...
    def get_resource_preemption_result(self, result_id: str) -> ResourcePreemptionResult | None: ...
    def save_preemptive_resource_definition(self, definition: PreemptiveResourceDefinition) -> None: ...
    def save_preemptive_resource_demand(self, demand: PreemptiveResourceDemand) -> None: ...
    def delete_preemptive_resource_demand(self, request_id: str) -> None: ...
    def save_preemptive_resource_reservation(self, reservation: PreemptiveResourceReservation) -> None: ...
    def delete_preemptive_resource_reservation(self, reservation_id: str) -> None: ...
    def save_preemptive_resource_release_intent(self, intent: PreemptiveResourceReleaseIntent) -> None: ...
    def delete_preemptive_resource_release_intent(self, intent_id: str) -> None: ...
    def save_resource_preemption_result(self, result: ResourcePreemptionResult) -> None: ...
    def set_committed_tick(self, tick: int) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class Persistence(Protocol):
    def transaction(self) -> AbstractContextManager[UnitOfWork]: ...
    def committed_tick(self) -> int: ...
    def events(self) -> tuple[DomainEvent, ...]: ...
    def command(self, command_id: str) -> Command | None: ...
    def scheduled_work(self) -> tuple[ScheduledWork, ...]: ...
    def due_scheduled_work(self, at: datetime) -> tuple[ScheduledWork, ...]: ...
    def simulation_position(self) -> SimulationPosition | None: ...
    def scenario_state(self) -> ScenarioRuntimeState | None: ...
    def resource_definitions(self) -> tuple[ResourceDefinition, ...]: ...
    def resource_demands(self) -> tuple[ResourceDemand, ...]: ...
    def resource_reservations(self) -> tuple[ResourceReservation, ...]: ...
    def resource_release_intents(self) -> tuple[ResourceReleaseIntent, ...]: ...
    def store_definitions(self) -> tuple[StoreDefinition, ...]: ...
    def store_items(self) -> tuple[DurableStoreItem, ...]: ...
    def store_put_intents(self) -> tuple[StorePutIntent, ...]: ...
    def store_get_requests(self) -> tuple[StoreGetRequest, ...]: ...
    def store_get_results(self) -> tuple[StoreGetResult, ...]: ...
    def container_definitions(self) -> tuple[ContainerDefinition, ...]: ...
    def container_states(self) -> tuple[ContainerState, ...]: ...
    def container_operation_intents(self) -> tuple[ContainerOperationIntent, ...]: ...
    def container_operation_results(self) -> tuple[ContainerOperationResult, ...]: ...
    def preemptive_resource_definitions(self) -> tuple[PreemptiveResourceDefinition, ...]: ...
    def preemptive_resource_demands(self) -> tuple[PreemptiveResourceDemand, ...]: ...
    def preemptive_resource_reservations(self) -> tuple[PreemptiveResourceReservation, ...]: ...
    def preemptive_resource_release_intents(self) -> tuple[PreemptiveResourceReleaseIntent, ...]: ...
    def resource_preemption_results(self) -> tuple[ResourcePreemptionResult, ...]: ...
