from sose.testing.conformance import ReferenceCapability as C
from sose.testing.conformance import ReferenceContract


def _evidence(**values):
    return {
        getattr(C, key.upper()): tuple(paths)
        for key, paths in values.items()
    }


REFERENCE_CATALOG = (
    ReferenceContract(
        domain="Maintenance / MRO",
        package="sose.examples.mro",
        docs_dir="docs/examples/mro",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.PREEMPTION, C.PROBABILISTIC_TRANSITIONS,
        }),
        evidence=_evidence(
            statecharts=("tests/test_mro_probabilistic_gating.py",),
            happy_path=("tests/test_mro_reference_happy_path.py",),
            sad_paths=("tests/test_mro_sad_paths.py",),
            restart_equivalence=("tests/test_mro_restart_equivalence.py",),
            scenarios=("tests/test_mro_scenarios.py",),
            resources=("tests/test_mro_sad_paths.py",),
            preemption=("tests/test_mro_emergency_preemption.py",),
            probabilistic_transitions=("tests/test_mro_probabilistic_gating.py",),
        ),
    ),
    ReferenceContract(
        domain="Procure-to-Pay",
        package="sose.examples.p2p",
        docs_dir="docs/examples/procure-to-pay",
        runtime_entrypoints=("build_runtime", "seed_happy_path"),
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK,
        }),
        evidence=_evidence(
            statecharts=("tests/test_p2p_happy_path.py",),
            happy_path=("tests/test_p2p_happy_path.py",),
            sad_paths=("tests/test_p2p_receipt_exceptions.py", "tests/test_p2p_shortage_backorder.py"),
            restart_equivalence=("tests/test_p2p_restart_equivalence.py",),
            scenarios=("tests/test_p2p_scenarios.py",),
            resources=("tests/test_p2p_receiving_resources.py",),
            scheduled_work=("tests/test_p2p_restart_equivalence.py",),
        ),
    ),
    ReferenceContract(
        domain="Manufacturing",
        package="sose.examples.manufacturing",
        docs_dir="docs/examples/manufacturing",
        runtime_entrypoints=("build_runtime", "seed_happy_path"),
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.PREEMPTION, C.PROBABILISTIC_TRANSITIONS,
        }),
        evidence=_evidence(
            statecharts=("tests/test_manufacturing_happy_path.py",),
            happy_path=("tests/test_manufacturing_happy_path.py",),
            sad_paths=("tests/test_manufacturing_quality_rework.py", "tests/test_manufacturing_breakdown.py"),
            restart_equivalence=("tests/test_manufacturing_restart_equivalence.py",),
            scenarios=("tests/test_manufacturing_scenarios.py",),
            resources=("tests/test_manufacturing_resources.py",),
            preemption=("tests/test_manufacturing_breakdown.py",),
            probabilistic_transitions=("tests/test_manufacturing_quality_rework.py",),
        ),
    ),
    ReferenceContract(
        domain="Logistics & transport",
        package="sose.examples.logistics",
        docs_dir="docs/examples/logistics",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.STORE_SELECTION,
        }),
        evidence=_evidence(
            statecharts=("tests/test_logistics_statecharts.py",),
            happy_path=("tests/test_logistics_happy_path.py",),
            sad_paths=("tests/test_logistics_contention.py",),
            restart_equivalence=("tests/test_logistics_restart_equivalence.py",),
            scenarios=("tests/test_logistics_scenarios.py",),
            resources=("tests/test_logistics_contention.py",),
            scheduled_work=("tests/test_logistics_restart_equivalence.py",),
            store_selection=("tests/test_logistics_happy_path.py",),
        ),
    ),
    ReferenceContract(
        domain="Cards & payments",
        package="sose.examples.cards_payments",
        docs_dir="docs/examples/cards-payments",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_cards_payments_statecharts.py",),
            happy_path=("tests/test_cards_payments_happy_paths.py",),
            sad_paths=("tests/test_cards_payments_reversal.py",),
            restart_equivalence=("tests/test_cards_payments_restart_equivalence.py",),
            scenarios=("tests/test_cards_payments_scenarios.py",),
            resources=("tests/test_cards_payments_happy_paths.py",),
            scheduled_work=("tests/test_cards_payments_restart_equivalence.py",),
            immutable_occurrences=("tests/test_cards_payments_reversal.py",),
        ),
    ),
    ReferenceContract(
        domain="IT service management",
        package="sose.examples.itsm",
        docs_dir="docs/examples/itsm",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.STORE_SELECTION,
            C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_itsm_statecharts.py",),
            happy_path=("tests/test_itsm_happy_paths.py",),
            sad_paths=("tests/test_itsm_reopen.py",),
            restart_equivalence=("tests/test_itsm_restart_equivalence.py",),
            scenarios=("tests/test_itsm_scenarios.py",),
            resources=("tests/test_itsm_happy_paths.py",),
            scheduled_work=("tests/test_itsm_restart_equivalence.py",),
            store_selection=("tests/test_itsm_priority_queue.py",),
            immutable_occurrences=("tests/test_itsm_reopen.py",),
        ),
    ),
    ReferenceContract(
        domain="Hospitals",
        package="sose.examples.hospitals",
        docs_dir="docs/examples/hospitals",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.STORE_SELECTION, C.PREEMPTION,
            C.ILLEGAL_PREREQUISITES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_hospitals_statecharts.py",),
            happy_path=("tests/test_hospitals_happy_paths.py",),
            sad_paths=("tests/test_hospitals_transfer.py",),
            restart_equivalence=("tests/test_hospitals_restart_equivalence.py",),
            scenarios=("tests/test_hospitals_scenarios.py",),
            resources=("tests/test_hospitals_happy_paths.py",),
            store_selection=("tests/test_hospitals_priority_queue.py",),
            preemption=("tests/test_hospitals_transfer.py",),
            illegal_prerequisites=("tests/test_hospitals_invariants.py",),
        ),
    ),
    ReferenceContract(
        domain="Construction",
        package="sose.examples.construction",
        docs_dir="docs/examples/construction",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.CRASH_RECOVERY,
            C.ILLEGAL_PREREQUISITES, C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_construction_statecharts.py",),
            happy_path=("tests/test_construction_happy_paths.py",),
            sad_paths=("tests/test_construction_contention.py",),
            restart_equivalence=("tests/test_construction_restart_equivalence.py",),
            scenarios=("tests/test_construction_scenarios.py",),
            resources=("tests/test_construction_contention.py",),
            scheduled_work=("tests/test_construction_scheduling.py",),
            crash_recovery=("tests/test_construction_crash_recovery.py",),
            illegal_prerequisites=("tests/test_construction_prerequisites.py",),
            immutable_occurrences=("tests/test_construction_happy_paths.py",),
        ),
    ),
    ReferenceContract(
        domain="Order-to-Cash",
        package="sose.examples.order_to_cash",
        docs_dir="docs/examples/order-to-cash",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.ILLEGAL_PREREQUISITES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_order_to_cash_statecharts.py",),
            happy_path=("tests/test_order_to_cash_runtime.py",),
            sad_paths=("tests/test_order_to_cash_runtime.py",),
            restart_equivalence=("tests/test_order_to_cash_restart_equivalence.py",),
            scenarios=("tests/test_order_to_cash_scenarios.py",),
            resources=("tests/test_order_to_cash_runtime.py",),
            scheduled_work=("tests/test_order_to_cash_restart_equivalence.py",),
            illegal_prerequisites=("tests/test_order_to_cash_runtime.py",),
        ),
    ),
    ReferenceContract(
        domain="Record-to-Report",
        package="sose.examples.record_to_report",
        docs_dir="docs/examples/record-to-report",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.CRASH_RECOVERY,
            C.ILLEGAL_PREREQUISITES, C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_record_to_report_statecharts.py",),
            happy_path=("tests/test_record_to_report_happy_paths.py",),
            sad_paths=("tests/test_record_to_report_reopen.py",),
            restart_equivalence=("tests/test_record_to_report_restart_equivalence.py",),
            scenarios=("tests/test_record_to_report_scenarios.py",),
            resources=("tests/test_record_to_report_happy_paths.py",),
            scheduled_work=("tests/test_record_to_report_restart_equivalence.py",),
            crash_recovery=("tests/test_record_to_report_crash_recovery.py",),
            illegal_prerequisites=("tests/test_record_to_report_invariants.py",),
            immutable_occurrences=("tests/test_record_to_report_happy_paths.py",),
        ),
    ),
    ReferenceContract(
        domain="Insurance",
        package="sose.examples.insurance",
        docs_dir="docs/examples/insurance",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.STORE_SELECTION,
            C.CRASH_RECOVERY, C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_insurance_statecharts.py",),
            happy_path=("tests/test_insurance_happy_path.py",),
            sad_paths=("tests/test_insurance_exceptions.py",),
            restart_equivalence=("tests/test_insurance_restart_equivalence.py",),
            scenarios=("tests/test_insurance_scenarios.py",),
            resources=("tests/test_insurance_happy_path.py",),
            scheduled_work=("tests/test_insurance_restart_equivalence.py",),
            store_selection=("tests/test_insurance_happy_path.py",),
            crash_recovery=("tests/test_insurance_crash_recovery.py",),
            immutable_occurrences=("tests/test_insurance_exceptions.py",),
        ),
    ),
    ReferenceContract(
        domain="Airports",
        package="sose.examples.airports",
        docs_dir="docs/examples/airports",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.STORE_SELECTION,
            C.CRASH_RECOVERY,
        }),
        evidence=_evidence(
            statecharts=("tests/test_airports_statecharts.py",),
            happy_path=("tests/test_airports_happy_path.py",),
            sad_paths=("tests/test_airports_scenarios.py",),
            restart_equivalence=("tests/test_airports_restart_equivalence.py",),
            scenarios=("tests/test_airports_scenarios.py",),
            resources=("tests/test_airports_happy_path.py",),
            scheduled_work=("tests/test_airports_restart_equivalence.py",),
            store_selection=("tests/test_airports_crash_recovery.py",),
            crash_recovery=("tests/test_airports_crash_recovery.py",),
        ),
    ),
    ReferenceContract(
        domain="Aviation",
        package="sose.examples.aviation",
        docs_dir="docs/examples/aviation",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.STORE_SELECTION,
            C.PREEMPTION, C.CRASH_RECOVERY,
        }),
        evidence=_evidence(
            statecharts=("tests/test_aviation_statecharts.py",),
            happy_path=("tests/test_aviation_happy_path.py",),
            sad_paths=("tests/test_aviation_aog.py",),
            restart_equivalence=("tests/test_aviation_restart_equivalence.py",),
            scenarios=("tests/test_aviation_scenarios.py",),
            resources=("tests/test_aviation_happy_path.py",),
            scheduled_work=("tests/test_aviation_restart_equivalence.py",),
            store_selection=("tests/test_aviation_restart_equivalence.py",),
            preemption=("tests/test_aviation_aog.py",),
            crash_recovery=("tests/test_aviation_crash_recovery.py",),
        ),
    ),
    ReferenceContract(
        domain="Credit and loans",
        package="sose.examples.credit_loans",
        docs_dir="docs/examples/credit-loans",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.CRASH_RECOVERY,
            C.PROBABILISTIC_TRANSITIONS, C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_credit_loans_statecharts.py",),
            happy_path=("tests/test_credit_loans_happy_path.py",),
            sad_paths=("tests/test_credit_loans_delinquency.py",),
            restart_equivalence=("tests/test_credit_loans_restart_equivalence.py",),
            scenarios=("tests/test_credit_loans_scenarios.py",),
            resources=("tests/test_credit_loans_happy_path.py",),
            scheduled_work=("tests/test_credit_loans_restart_equivalence.py",),
            crash_recovery=("tests/test_credit_loans_restart_equivalence.py",),
            probabilistic_transitions=("tests/test_credit_loans_statecharts.py",),
            immutable_occurrences=("tests/test_credit_loans_restart_equivalence.py",),
        ),
    ),
    ReferenceContract(
        domain="Telecommunications",
        package="sose.examples.telecom",
        docs_dir="docs/examples/telecom",
        runtime_entrypoints=("build_runtime", "seed_reference"),
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_telecom_statecharts.py",),
            happy_path=("tests/test_telecom_happy_path.py",),
            sad_paths=("tests/test_telecom_sad_paths.py",),
            restart_equivalence=("tests/test_telecom_restart_equivalence.py",),
            scenarios=("tests/test_telecom_scenarios.py",),
            resources=("tests/test_telecom_scenarios.py",),
            scheduled_work=("tests/test_telecom_restart_equivalence.py",),
            immutable_occurrences=("tests/test_telecom_restart_equivalence.py",),
        ),
    ),
    ReferenceContract(
        domain="Energy / Utilities",
        package="sose.examples.energy_utilities",
        docs_dir="docs/examples/energy-utilities",
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.SCHEDULED_WORK, C.ILLEGAL_PREREQUISITES,
            C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_energy_utilities_statecharts.py",),
            happy_path=("tests/test_energy_utilities_happy_path.py",),
            sad_paths=("tests/test_energy_utilities_sad_paths.py",),
            restart_equivalence=("tests/test_energy_utilities_restart_equivalence.py",),
            scenarios=("tests/test_energy_utilities_scenarios.py",),
            scheduled_work=("tests/test_energy_utilities_restart_equivalence.py",),
            illegal_prerequisites=("tests/test_energy_utilities_sad_paths.py",),
            immutable_occurrences=(
                "tests/test_energy_utilities_sad_paths.py",
                "tests/test_energy_utilities_restart_equivalence.py",
            ),
        ),
    ),
    ReferenceContract(
        domain="Public Transit / Rail",
        package="sose.examples.transit",
        docs_dir="docs/examples/transit",
        runtime_entrypoints=("build_runtime", "seed_reference"),
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.SCHEDULED_WORK, C.ILLEGAL_PREREQUISITES,
            C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_transit_statecharts.py",),
            happy_path=("tests/test_transit_happy_path.py",),
            sad_paths=("tests/test_transit_sad_paths.py",),
            restart_equivalence=("tests/test_transit_restart_equivalence.py",),
            scenarios=("tests/test_transit_scenarios.py",),
            scheduled_work=(
                "tests/test_transit_sad_paths.py",
                "tests/test_transit_restart_equivalence.py",
            ),
            illegal_prerequisites=("tests/test_transit_sad_paths.py",),
            immutable_occurrences=(
                "tests/test_transit_sad_paths.py",
                "tests/test_transit_restart_equivalence.py",
            ),
        ),
    ),
    ReferenceContract(
        domain="Field Service / Workforce",
        package="sose.examples.field_service",
        docs_dir="docs/examples/field-service",
        runtime_entrypoints=("build_runtime", "seed_reference"),
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCENARIOS, C.RESOURCES, C.SCHEDULED_WORK, C.STORE_SELECTION,
            C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_field_service_statecharts.py",),
            happy_path=("tests/test_field_service_happy_path.py",),
            sad_paths=("tests/test_field_service_sad_paths.py",),
            restart_equivalence=("tests/test_field_service_restart_equivalence.py",),
            scenarios=("tests/test_field_service_scenarios.py",),
            resources=("tests/test_field_service_happy_path.py",),
            scheduled_work=("tests/test_field_service_restart_equivalence.py",),
            store_selection=("tests/test_field_service_happy_path.py",),
            immutable_occurrences=("tests/test_field_service_sad_paths.py",),
        ),
    ),
    ReferenceContract(
        domain="Hospitality / Reservations",
        package="sose.examples.hospitality",
        docs_dir="docs/examples/hospitality",
        runtime_entrypoints=("build_runtime", "seed_reference"),
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCHEDULED_WORK, C.ILLEGAL_PREREQUISITES, C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_hospitality_statecharts.py",),
            happy_path=("tests/test_hospitality_happy_path.py",),
            sad_paths=("tests/test_hospitality_sad_paths.py",),
            restart_equivalence=("tests/test_hospitality_restart_equivalence.py",),
            scheduled_work=("tests/test_hospitality_restart_equivalence.py",),
            illegal_prerequisites=("tests/test_hospitality_sad_paths.py",),
            immutable_occurrences=(
                "tests/test_hospitality_sad_paths.py",
                "tests/test_hospitality_restart_equivalence.py",
            ),
        ),
    ),
    ReferenceContract(
        domain="Warehouse / Fulfillment",
        package="sose.examples.warehouse_fulfillment",
        docs_dir="docs/examples/warehouse-fulfillment",
        runtime_entrypoints=("build_runtime", "seed_reference"),
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.ILLEGAL_PREREQUISITES, C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_warehouse_fulfillment_statecharts.py",),
            happy_path=("tests/test_warehouse_fulfillment_happy_path.py",),
            sad_paths=("tests/test_warehouse_fulfillment_sad_paths.py",),
            restart_equivalence=(
                "tests/test_warehouse_fulfillment_restart_equivalence.py",
            ),
            illegal_prerequisites=("tests/test_warehouse_fulfillment_sad_paths.py",),
            immutable_occurrences=(
                "tests/test_warehouse_fulfillment_happy_path.py",
                "tests/test_warehouse_fulfillment_sad_paths.py",
                "tests/test_warehouse_fulfillment_restart_equivalence.py",
            ),
        ),
    ),
    ReferenceContract(
        domain="Subscription / SaaS",
        package="sose.examples.subscription_saas",
        docs_dir="docs/examples/subscription-saas",
        runtime_entrypoints=("build_runtime", "seed_reference"),
        capabilities=frozenset({
            C.STATECHARTS, C.HAPPY_PATH, C.SAD_PATHS, C.RESTART_EQUIVALENCE,
            C.SCHEDULED_WORK, C.ILLEGAL_PREREQUISITES, C.IMMUTABLE_OCCURRENCES,
        }),
        evidence=_evidence(
            statecharts=("tests/test_subscription_saas_statecharts.py",),
            happy_path=("tests/test_subscription_saas_happy_path.py",),
            sad_paths=("tests/test_subscription_saas_sad_paths.py",),
            restart_equivalence=(
                "tests/test_subscription_saas_restart_equivalence.py",
            ),
            scheduled_work=(
                "tests/test_subscription_saas_sad_paths.py",
                "tests/test_subscription_saas_restart_equivalence.py",
            ),
            illegal_prerequisites=("tests/test_subscription_saas_sad_paths.py",),
            immutable_occurrences=(
                "tests/test_subscription_saas_happy_path.py",
                "tests/test_subscription_saas_restart_equivalence.py",
            ),
        ),
    ),
)
